# Generated by Django 3.0.3 on 2020-05-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
    ]
