# Generated by Django 3.0.3 on 2020-05-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
    ]
