# Generated by Django 3.0.3 on 2020-05-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_listing_lot_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
