# Generated by Django 3.0.3 on 2020-05-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200503_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=models.TextField(blank=True, default='Private'),
        ),
    ]
